apiVersion: v1
kind: Service
metadata:
  name: quicknote-app
  labels:
    app: quicknote
spec:
  type: NodePort
  externalTrafficPolicy: Local
  # External access is provided via Ingress (see 07-ingress.yaml)
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    # Default points to blue version
    # To switch to green, change version: green
    # For Jenkins deployment, use: kubectl patch service quicknote-app -p '{"spec":{"selector":{"version":"green"}}}'
    app: quicknote
    version: blue
