apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quicknote-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cf
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/compute-full-forwarded-for: "true"
    nginx.ingress.kubernetes.io/proxy-real-ip-cidr: "0.0.0.0/0"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - quicknote.cloud.aw3.dev
    secretName: quicknote-tls
  rules:
  - host: quicknote.cloud.aw3.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quicknote-app
            port:
              number: 80
---
