apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  db-user: "example_user"
  db-name: "example_db"
  db-password: "example_pass"

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-ecr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: your_docker_json_base64
# kubectl -n quicknote create secret docker-registry aws-ecr-secret \
# --docker-server=<account-id>.dkr.ecr.us-east-1.amazonaws.com \
# --docker-username=AWS \
# --docker-password=$(aws ecr get-login-password --region us-east-1) \
# --dry-run=client -o yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  flask-secret-key: "very-strong-secret-key-change-this-secret-as-soon-as-possible"
---
