apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  db-user: "example_user"
  db-name: "example_db"
  db-password: "example_pass"

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-ecr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: your_docker_json_base64
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  flask-secret-key: "very-strong-secret-key-change-this-secret-as-soon-as-possible"
---
